version: "3"
services:

  vttestserver57:
    image: vitess/vttestserver:mysql57
    restart: always
    ports:
      - 33577:33577
    environment:
      PORT: 33574
      KEYSPACES: apply_migrations_with_an_empty_migrations_folder_works,applying_a_single_migration_should_work,applying_two_migrations_works,migrations_should_fail_when_the_script_is_invalid,migrations_should_not_reapply_modified_migrations,migrations_should_fail_on_an_uninitialized_nonempty_databas,migrations_should_succeed_on_an_uninitialized_nonempty_data,basic_create_migration_works
      NUM_SHARDS: 1,1,1,1,1,1,1,1
      MYSQL_BIND_HOST: "0.0.0.0"

  vttestserver80:
    image: vitess/vttestserver:mysql80
    restart: always
    ports:
      - 33807:33807
    environment:
      PORT: 33804
      KEYSPACES: test
      NUM_SHARDS: "1"
      MYSQL_BIND_HOST: "0.0.0.0"
