version: "3"
services:

  vttestserver57:
    image: vitess/vttestserver:mysql57
    restart: always
    ports:
      - 33577:33577
    environment:
      PORT: 33574
      KEYSPACES: test
      NUM_SHARDS: "1"
      MYSQL_BIND_HOST: "0.0.0.0"

  vttestserver80:
    image: vitess/vttestserver:mysql80
    restart: always
    ports:
      - 33807:33807
    environment:
      PORT: 33804
      KEYSPACES: test
      NUM_SHARDS: "1"
      MYSQL_BIND_HOST: "0.0.0.0"
