name: vttestserver docker
on:
  push:

jobs:

  test:
    name: "vttestserver docker"
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker-compose up -d
      
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - run: mysql -h 127.0.0.1 -P 33577 -u root -pprisma -e "SHOW DATABASES;"
          
      - run: docker ps -a
        if: ${{ always() }}
      - run: docker logs vttestserver-tests_vttestserver80_1
        if: ${{ always() }}
